import { useState } from 'react'
import './App.css'
const currentYear = new Date().getFullYear()
const email = 'victorlorenzzopg@gmail.com'
const linkedin = 'https://www.linkedin.com/in/victor-lorenzzo-penaroti-47870b356/'
const projects = [
  { id: '01', category: 'Software', label: 'ENGENHARIA DE SOFTWARE', title: 'Da ideia à arquitetura.', description: 'Projetos integradores e de extensão na UNIP: engenharia de requisitos, modelagem de processos e arquitetura de sistemas, com estudos em estruturas de dados e inteligência artificial.', tags: ['Projetos acadêmicos', 'Lógica de programação', 'IA'] },
  { id: '02', category: 'Dados & automação', label: 'AUTOMAÇÃO & DADOS', title: 'Dados com propósito.', description: 'Scripts em Python para manipular, limpar e organizar dados. Modelagem de bancos relacionais com diagramas E-R e consultas SQL para extração e análise de informações.', tags: ['Python', 'SQL', 'Modelagem de dados'] },
]
function App() {
 const [menu, setMenu] = useState(false)
 const [filter, setFilter] = useState('Todos')
 const [copied, setCopied] = useState(false)
 async function copyEmail() { try { await navigator.clipboard.writeText(email); setCopied(true); window.setTimeout(() => setCopied(false), 3000) } catch { window.location.href = `mailto:${email}` } }
 return <>
  <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
  <header className="header"><a href="#inicio" className="logo" aria-label="Victor Lorenzzo, início">vl<span>.</span></a><button className="menu-toggle" aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? 'Fechar −' : 'Menu +'}</button><nav id="navigation" className={menu ? 'open' : ''} aria-label="Navegação principal">{[['Sobre','sobre'],['Projetos','projetos'],['Trajetória','trajetoria'],['Habilidades','habilidades']].map(([label,id]) => <a href={`#${id}`} key={id} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#contato" onClick={() => setMenu(false)}>Vamos conversar <span aria-hidden="true">↗</span></a></nav></header>
  <main id="conteudo">
   <section id="inicio" className="wrap hero"><div className="hero-copy"><p className="eyebrow"><i className="dot" /> CÓDIGO, CURIOSIDADE & POSSIBILIDADES</p><p className="hello">Olá, eu sou o Victor.</p><h1>Transformando<br/>lógica em<br/><em>possibilidades.</em></h1><p className="intro">Estudante de Análise e Desenvolvimento de Sistemas. Explorando software, dados e automação para construir soluções que fazem sentido.</p><div className="actions"><a className="button" href="#projetos">Conheça meus projetos <span aria-hidden="true">↗</span></a><a className="text-link" href="./curriculo-victor.pdf" download>Baixar currículo <span aria-hidden="true">↓</span></a></div><div className="location"><span aria-hidden="true">◎</span> São Paulo, Brasil <i/> <a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><div className="portrait"><span className="cross" aria-hidden="true">+</span><div className="photo"><img src="./victor.jpg" alt="Victor Lorenzzo, de óculos escuros e jaqueta preta" fetchPriority="high"/><div className="caption">VICTOR LORENZZO<small>DESENVOLVEDOR EM FORMAÇÃO</small></div></div><div className="floating"><b aria-hidden="true">&lt;/&gt;</b><div>Aprender. Construir. Evoluir.<small>Uma linha de código por vez.</small></div></div><span className="coordinates">23°33′ S &nbsp; 46°38′ W</span></div><div className="hero-bottom"><span>TECNOLOGIA COM INTENÇÃO.</span><a href="#sobre">Explore o portfólio ↓</a><span>01 — 05</span></div></section>
   <div className="ribbon"><div className="wrap">{['Python','Java','C / C++','SQL','Git','Excel avançado'].map(t => <span key={t}><i aria-hidden="true">✳</i>{t}</span>)}</div></div>
   <section className="wrap section about" id="sobre"><div><p className="eyebrow">01 / SOBRE MIM</p><h2>Curiosidade é o<br/>meu ponto de <em>partida.</em></h2></div><div className="about-copy"><p>Sou Victor Lorenzzo Penaroti Gomes, estudante de Análise e Desenvolvimento de Sistemas na UNIP, em São Paulo. Meu interesse está em entender problemas e transformar esse conhecimento em soluções de software.</p><p>Minha trajetória reúne atendimento ao cliente, organização de dados e projetos acadêmicos. Hoje, aprofundo meus conhecimentos em programação, inteligência artificial e automação, conectando o lado técnico à experiência com pessoas.</p><div className="facts"><div><strong>UNIP</strong><small>Análise e Desenvolvimento de Sistemas</small></div><div><strong>Jun. 2028</strong><small>Previsão de conclusão</small></div></div></div></section>
   <section className="wrap section" id="projetos"><div className="section-heading"><div><p className="eyebrow">02 / PROJETOS</p><h2>Conhecimento em <em>prática.</em></h2></div><p>Do aprendizado à aplicação.<br/>Um pouco do que venho construindo.</p></div><div className="filters" aria-label="Filtrar projetos">{['Todos','Software','Dados & automação'].map(f => <button key={f} onClick={() => setFilter(f)} aria-pressed={filter === f} className={filter === f ? 'selected' : ''}>{f}{f === 'Todos' && <span>02</span>}</button>)}</div><div className="projects">{projects.filter(p => filter === 'Todos' || p.category === filter).map(p => <article className="project" key={p.id}><div className={`project-art art-${p.id}`} aria-hidden="true"><span className="art-label">{p.id === '01' ? 'SYSTEM / BLUEPRINT' : 'DATA / WORKFLOW'}</span>{p.id === '01' ? <div className="diagram"><b>&lt;/&gt;</b><div><span>interface</span><span>lógica</span><span>dados</span></div></div> : <div className="code"><div><span>01</span> import pandas as pd</div><div><span>02</span> dados = carregar_dados()</div><div><span>03</span> dados.limpar().transformar()</div><p>✓ dados prontos para analisar</p></div>}<span className="art-number">/{p.id}</span></div><div className="project-body"><p className="eyebrow">{p.label}</p><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div><a className="project-link" href={`mailto:${email}?subject=${encodeURIComponent(`Quero saber mais: ${p.title}`)}`}>Conversar sobre o projeto <span aria-hidden="true">↗</span></a></div></article>)}</div></section>
   <div className="journey-band"><section className="wrap section journey" id="trajetoria"><div><p className="eyebrow">03 / TRAJETÓRIA</p><h2>Cada experiência,<br/>um novo <em>aprendizado.</em></h2><p className="muted">Tecnologia, comunicação e colaboração<br/>se encontram no meu caminho.</p><a className="text-link" href="./curriculo-victor.pdf" download>Ver currículo completo ↓</a></div><div className="timeline"><article><p className="date">FORMAÇÃO · CONCLUSÃO PREVISTA EM JUN. 2028</p><h3>Análise e Desenvolvimento de Sistemas</h3><h4>UNIP · Universidade Paulista</h4><p>Formação tecnológica com projetos integradores, modelagem de sistemas e fundamentos de desenvolvimento de software.</p></article><article><p className="date">FEV. 2025 — JUL. 2025</p><h3>Auxiliar de Atendimento ao Cliente</h3><h4>Oracle</h4><p>Suporte a clientes por canais digitais, organização de planilhas operacionais no Excel e apoio às rotinas administrativas e de comunicação.</p></article><article><p className="date">2021 — 2023</p><h3>Liderança & eventos de tecnologia</h3><h4>Grêmio estudantil e feiras escolares</h4><p>Um ano de atuação no grêmio estudantil, com gestão de projetos e comunicação. Participação e organização de feiras de profissões e tecnologia ao longo do ciclo escolar.</p></article></div></section></div>
   <section className="wrap section" id="habilidades"><div className="section-heading"><div><p className="eyebrow">04 / HABILIDADES</p><h2>Minha caixa de <em>ferramentas.</em></h2></div><p>Uma base sólida.<br/>Sempre em desenvolvimento.</p></div><div className="skills"><article><span className="skill-icon" aria-hidden="true">&lt;/&gt;</span><h3>Programação</h3><p>Lógica para transformar problemas em soluções.</p><div className="tags">{['C / C++','Java','Python','SQL','HTML','CSS','JavaScript','TypeScript','React','Node.js','APIs REST','Autenticação','Testes automatizados'].map(t => <span key={t}>{t}</span>)}</div></article><article><span className="skill-icon" aria-hidden="true">▤</span><h3>Dados & ferramentas</h3><p>Organização, análise e desenvolvimento.</p><div className="tags">{['Git','Bancos relacionais','Excel avançado','Pacote Office','Lógica de jogos'].map(t => <span key={t}>{t}</span>)}</div></article><article><span className="skill-icon" aria-hidden="true">◎</span><h3>Além do código</h3><p>Comunicação que conecta pessoas e ideias.</p><ul className="languages"><li>Português <span>Nativo</span></li><li>Inglês <span>Avançado / C1</span></li><li>Espanhol <span>Intermediário / B1</span></li></ul></article></div><p className="interests"><span>NO MEU RADAR</span> Inteligência artificial · Engenharia de software · Análise de sistemas · Automação</p></section>
   <section className="wrap section contact" id="contato"><p className="eyebrow">05 / VAMOS CONVERSAR</p><h2>Boas ideias começam<br/>com uma <em>conversa.</em></h2><p>Tem uma oportunidade ou um projeto em mente?<br/>Vamos conectar ideias e construir o próximo passo.</p><div className="contact-actions"><a className="button" href={`mailto:${email}`}>Entre em contato <span aria-hidden="true">↗</span></a><a className="button whatsapp-button" href="https://wa.me/5511959097468" target="_blank" rel="noopener noreferrer" aria-label="Conversar no WhatsApp com +55 11 95909-7468">Conversar no WhatsApp <span aria-hidden="true">↗</span></a></div><div className="contact-links"><button onClick={copyEmail}>{copied ? 'E-mail copiado!' : email} <span aria-hidden="true">⧉</span></button><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="tel:+5511959097468">(11) 95909-7468 ↗</a></div><span role="status" className="sr-only">{copied ? 'E-mail copiado para a área de transferência.' : ''}</span></section>
  </main><footer className="wrap footer"><a href="#inicio" className="logo" aria-label="Voltar ao início">vl<span>.</span></a><p>© {currentYear} Victor Lorenzzo. Feito com intenção.</p><a href="#inicio">De volta ao topo ↑</a></footer>
 </>
}
export default App






